build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/SwaggerPublisher.java

Next PR will introduce fiegn client and along with it web filters will be applied. This will not work with current tests which use mock mvc as app insights web filters are not initialised but are executed. Fixing in advance.
Note. This is known issue and applied in other projects as well
```
[ ] Yes
[x] No
```

Fix gradle verification tasks

---

src/main/resources/db/migration/V002__Notifications_default_created_at.sql

https://tools.hmcts.net/jira/browse/BPS-1088
Added DEFAULT NOW() to the definition of created_at field
```
[ ] Yes
[x] No
```

Added DEFAULT NOW() to created_at field definition

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationStatus.java

After retrieving all notifications (#30 + #31) and sending all to API (TBD), we need to mark them as SENT. Doing separate DB interaction in this - separate PR so it can be orchestrated easily in the future
```
[ ] Yes
[x] No
```

Add mark as sent method for updating notifications after pushing to API

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java

As being fast pacing I've missed another step from notifying client API which requires action in DB - marking as failed. Could've included as part of #32 but hey - we can say everything is extra separate now :man_shrugging: 
```
[ ] Yes
[x] No
```

Add mark as failed repository method

---

src/main/java/uk/gov/hmcts/reform/notificationservice/task/PendingNotificationsTask.java
src/test/java/uk/gov/hmcts/reform/notificationservice/task/PendingNotificationsTaskTest.java

Task unit add - just a task. Next:
- scheduler config
- shedlock config
- enable task
```
[ ] Yes
[x] No
```

Add task for pending notifications

---

Jenkinsfile_CNP
build.gradle
src/functionalTest/resources/application.conf

Involved changes are:
- env vars for notification queue:
- PRs
- master
- bau: missed rest-assured version set. was behind 4.3.0 -> 3.3.0 :see_no_evil: 
- same set up is for smoke tests. reusing the config
```
[ ] Yes
[x] No
```

Prepare pipeline for functional tests

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

When something is unknown feign clients return status `-1` which fails to evaluate into Spring's `HttpStatus`. Using `resolve` method instead which returns null when status is not found
```
[ ] Yes
[x] No
```

Bug: secure feign exceptions with `-1` status

---

src/main/resources/db/migration/V006__Change_error_description_type.sql

https://tools.hmcts.net/jira/browse/BPS-1087
Type of 'reason' field in process_events table in the processor DB is TEXT (nullable). Type of 'error_description' field in notifications table is VARCHAR(255) (non-nullable). It appeared that some values in 'reason' field in processor DB exceed 255 characters, this prevents import of existing notifications from processor.
Suggestion is to change type of 'error_description' field to TEXT (non-nullable, because there are no NULL values in 'reason' field in processor DB).
```
[ ] Yes
[x] No
```

Changed type of error_description

---

Jenkinsfile_CNP

master pipeline is sending/reading wrong queues. this has been deployed fairly recently and behind the scenes - service itself was not aware of it. changing to the correct ones (at least for one environment specifically effecting master build)
```
[ ] Yes
[x] No
```

Amend secrets used for staging pipelines

---

Jenkinsfile_CNP

For some reason missed the notes saying the changes are not yet applied so reverting secret names used for functional testing
```
[ ] Yes
[x] No
```

Revert changes made to secret names

---

Jenkinsfile_CNP
charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

use staging queue for testing.
just use the staging queue for aat-staging. default false.
I did not want to use missing bean condition or not want to use default queues connection-string in test queue condition, I want explicit configuration so create 'queue.notifications.staging-enabled' var. 
will update flux just before merge.
```
[ ] Yes
[x] No
```

use staging queue for testing

---

src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/model/out/NotificationInfo.java

Following changes from https://github.com/hmcts/reform-scan-notification-service/pull/84

Rename envelope api info model property

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/requirements.yaml

This introduces next iteration (instead of bug-fix), but since it's still v0 so moving to the v.0.1 instead. Fresh start for chart - comes with the smoke/functional test feature for flux manager.
So any next iteration can be treated freshly as mostly we introduce some flags and whatnot which is sort of minor version release
```
[ ] Yes
[x] No
```

Bump java chart 2.15 -> 2.18

---

src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java

Not quite related, but still: [Create alerts for scheduled tasks in Notification service](https://tools.hmcts.net/jira/browse/BPS-1190)
Making sure log entry is marking the end of task of consuming service bus notifications
```
[ ] Yes
[x] No
```

Amend log entry marking task ending

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/util/DateFormatter.java
src/test/java/uk/gov/hmcts/reform/notificationservice/util/CustomInstantSerializerTest.java

- Use local time instead of UTC
- remove miliseconds
Changes are applied in the `DateFormatter` class which is used by `CustomInstantSerializer`, which is used in annotations on response models datetime fields:
```java
@JsonSerialize(using = CustomInstantSerializer.class)
```
https://tools.hmcts.net/jira/browse/BPS-1284

Change timestamp format in api endpoints

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NewNotification.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandler.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapper.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapperTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java

https://tools.hmcts.net/jira/browse/BPS-1291
- Populate `message_id` column in the `notifications` table values with the queue message id 
```
[ ] Yes
[x] No
```

Populate message_id values in the notifications table

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/Notification.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationMapper.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/BPS-1291
`NotificationRespository` changes are missing in #190 
Add `message_id` to insert SQL statement to populate values.
```
[ ] Yes
[x] No
```

Update Notification repository to include message_id to the sql

---

Jenkinsfile_CNP
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/Configuration.java
src/functionalTest/resources/application.conf

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
Reviewing functional tests. READ was not used - removed
```
[ ] Yes
[x] No
```

Replace ServiceBus connection string with access key in functional tests

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/health/ReadinessTest.java
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/BPS-1347
The result of accessing /health/readiness endpoint looks like this:
{ "status": "UP", "components": { "db": { "status": "UP", "details": { "database": "PostgreSQL", "validationQuery": "isValid()" } }, "readinessState": { "status": "UP" } } }
**Does this PR introduce a breaking change? (check one with "x")**
[ ] Yes
[x] No

Added db to readiness. Integration test

---

.github/workflows/swagger.yml
build.gradle
charts/reform-scan-notification-service/Chart.yaml
gradle/wrapper/gradle-wrapper.properties

https://tools.hmcts.net/jira/browse/FACT-1698
All relevant Renovate dependency updates have been merged in.
**Major Version Update:**
- Open Feign V13
- Flyway V10
```
[ ] Yes
[x] No
```

FACT 1698 - Renovate Dependencies Update

---

.github/dependabot.yml
build.gradle
charts/reform-scan-notification-service/Chart.yaml
config/owasp/suppressions.xml
infrastructure/state.tf

https://tools.hmcts.net/jira/browse/FACT-1980
- Flyway/Postgresql version put into buildscript property to ease updating 
- Removed jackson-databind suppression but latest Azzure Messaging Servicebus is still bringing in vulnerable Azure libraries
- Removes dependabot.yml
**Major Version Jump**
- Rest Assured V5
```
[ ] Yes
[x] No
```

FACT-1980 - CVE and Dependency Updates

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/resources/db/migration/V012__remove_message_id_constraint.sql

Add DB migration script for testing. As the dm script drops the need for unique message IDs, the test for that has been disabled.
```
[ ] Yes
[x] No
```

FACT-1963 Adds db migration script for testing
