hmcts/reform-scan-notification-service

build.gradle
config/checkstyle/checkstyle.xml

Before starting to introduce anything new or update existing settings, a lot of legacy code is used in `build.gradle` file including some mess factor between the tasks. Aligning, sorting, updating. Ready to be used by dependabot and us. All but junit dependencies have been up-to-date.
Follow the commit history for separate steps taken to achieve the final state of the build file
```
[ ] Yes
[x] No
```

Upgrade gradle build

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml

https://tools.hmcts.net/jira/browse/BPS-1080
```
[ ] Yes
[x ] No
```

Added ingres and image config

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/bootstrap.yaml

[Process messages from DB](https://tools.hmcts.net/jira/browse/BPS-1092)
Helper PR for moving notification client out from blob router service
```
[ ] Yes
[x] No
```

Add secrets to charts

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/BPS-1086
```
[ ] Yes
[x] No
```

Add notifications database secrets

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationClientTest.java
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/notificationservice/Application.java
src/main/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationClient.java
src/main/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationConfiguration.java
src/main/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationRequest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/clients/ErrorNotificationResponse.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/HttpConfiguration.java

[Process messages from DB](https://tools.hmcts.net/jira/browse/BPS-1092)
Copy over the implementation done in blob router
```
[ ] Yes
[x] No
```

Add error notification client

---

build.gradle
charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/requirements.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

add queue config
I added small code to set up queue client to see config is working.
```
[ ] Yes
[x] No
```

add notification queue config

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/application.yaml

disable osba queue for aat and rename queue
```
[ ] Yes
[x] No
```

disable osba queue for aat and rename queue

---

Jenkinsfile_CNP
build.gradle
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/notificationservice/config/FlywayConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/PendingMigrationException.java
src/main/resources/application.yaml
src/main/resources/db/migration/V001__Create_notifications_table.sql

https://tools.hmcts.net/jira/browse/BPS-1086
```
[ ] Yes
[x] No
```

Add flyway config and migration script for notifications table

---

src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/NotificationServiceHealthTest.java

fix package name
```
[ ] Yes
[x] No
```

fix package name

---

build.gradle
src/main/java/uk/gov/hmcts/reform/notificationservice/exception/InvalidMessageException.java
src/main/java/uk/gov/hmcts/reform/notificationservice/model/request/incomming/NotificationMsg.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParser.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java

Add notification queue message parser
```
[ ] Yes
[x] No
```

Add notification message parser

---

charts/reform-scan-notification-service/values.preview.template.yaml

- Currently preview PR is trying to connect to AAT Postgres and hence failing with error
```
Client from Azure Virtual Networks is not allowed to access the server. Please make sure your Virtual Network is correctly configured.
```
```
[ ] Yes
[ x] No
```

Override key vault for preview otherwise it loads default values yaml

---

build.gradle
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NewNotification.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/Notification.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationMapper.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationStatus.java

Reference: #21 
```
[ ] Yes
[x] No
```

Add data/jdbc boilerplate

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
src/main/resources/db/migration/V003__Add_index_for_status.sql

[Process messages from DB](https://tools.hmcts.net/jira/browse/BPS-1092)
Includes a tiny re-jig of existing test case so I can re-use in the new one
```
[ ] Yes
[x] No
```

Add repo method for pending notifications

---

src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/resources/application.yaml

change queue client to IMessageReceiver
IMessageReceiver seems more powerful.
```
[ ] Yes
[x] No
```

change queue client to IMessageReceiver

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/resources/application.yaml

Add notifications max retry count
flux change: 
https://github.com/hmcts/cnp-flux-config/pull/2577
```
[ ] Yes
[x] No
```

Add max retry count

---

src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationStatus.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

[Publish message from DB](https://tools.hmcts.net/jira/browse/BPS-1092)
Introducing ~basic happy path scenario of~ getting pending notifications from DB to marking them as sent
```
[ ] Yes
[x] No
```

Add NotificationService

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml

https://tools.hmcts.net/jira/browse/BPS-1088
Flux: https://github.com/hmcts/cnp-flux-config/pull/2596
```
[ ] Yes
[x] No
```

Added S2S_URL

---

src/main/java/uk/gov/hmcts/reform/notificationservice/config/SchedulerConfiguration.java

Used across products/services within our team
```
[ ] Yes
[x] No
```

Feature: custom task scheduler

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/application.yaml

add notifications consume task configs.
next pr will be to add spring schedule task
```
[ ] Yes
[x] No
```

add notifications consume task configs

---

build.gradle
config/owasp/suppressions.xml
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/SchedulerConfigurationTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/SchedulerConfiguration.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/ShedlockConfiguration.java
src/main/resources/application.yaml
src/main/resources/db/migration/V004__Add_shedlock_table.sql

although each file suggests individual point but it comes as a package. except the suppression - tiny fix as `.js` no longer applies. i run check everytime i include or amend dependencies so it's up-to-date
```
[ ] Yes
[x] No
```

Add Shedlock configuration

---

src/main/java/uk/gov/hmcts/reform/notificationservice/model/in/NotificationMsg.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandler.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapper.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParser.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapperTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java

Proposed refactoring:
package model.request.incomming into model.in
This is in line with the package model.out which will appear in PR-43

Refactored package request.incomming into in

---

src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/notificationservice/Application.java
src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

add spring schedule to handle notification messages
```
[ ] Yes
[x] No
```

add notification task

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml
src/integrationTest/resources/application.properties
src/main/resources/application.yaml

This PR is just for config alone - about to enable task.
Flux PR will be linked shortly
```
[ ] Yes
[x] No
```

Add configs for pending notifications task

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/SchedulerConfigurationTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/task/PendingNotificationsTask.java

Enable pending notifications task

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java

Proposed refactoring:
- make private method private
- remove `@Transactional` annotation (db operation is the last step - nothing to roll back)
- make logging more readable

Clean up notification service

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

Replaced log pattern-breaking characters
The vulnerability is described here: https://cwe.mitre.org/data/definitions/117.html
```
[ ] Yes
[x] No
```

Replace log pattern-breaking characters

---

Jenkinsfile_CNP
build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/Configuration.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageDetails.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageHelper.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/RestAssuredHelper.java
src/functionalTest/resources/application.conf
src/functionalTest/resources/servicebus/message/valid-notification.json

Adding ~disabled~ test as we don't have controller yet.
Assertions are made in assumption of #61 
```
[ ] Yes
[x] No
```

Add functional test: push queue message, await for completion

---

src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/RestAssuredHelper.java

For now, master says 0 is not 1. Attaching helper description along with other assertion improvements so each step can be debugged easier
```
[ ] Yes
[x] No
```

Make test tools react more humanly

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java

Missed log entry informing us we are trying to send notification with details listed in it so trace doesn't look smth like following:
start job
found N notifications
failed
finished job
```
[ ] Yes
[x] No
```

Add extra log entry for completion

---

src/main/java/uk/gov/hmcts/reform/notificationservice/data/Notification.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java

Just to reduce the size of logging code in the `NotificationService` a bit.

Clean up logging

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java

https://tools.hmcts.net/jira/browse/BPS-1154

Log notification sending summary

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/BPS-1154

Handle all exceptions in notification service

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/exceptionhandler/ResponseExceptionHandler.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/AuthService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/AuthServiceTest.java

https://tools.hmcts.net/jira/browse/BPS-1088
Handling missing and corrupted s2s token
```
[ ] Yes
[ ] No
```

Handling missing and corrupted s2s token

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml

tune config values
```
[ ] Yes
[x] No
```

tune config values

---

src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java

The endpoint has been restored and notifications are being processed
```
[ ] Yes
[x] No
```

Amend assertions in functional test

---

README.md

https://tools.hmcts.net/jira/browse/BPS-1081
update read me
```
[ ] Yes
[x] No
```

Add purpose readme

---

build.gradle

to speed up pipeline bump the versions that dependabot tried, 
```
[ ] Yes
[x] No
```

manual dependabot, bump versions

---

src/main/java/uk/gov/hmcts/reform/notificationservice/data/Notification.java

Add 'container' field when logging information about the notification

Log container

---

Jenkinsfile_CNP

TTL: 11 days
```
[ ] Yes
[x] No
```

Remove deprecated flag for installing chart

---

infrastructure/main.tf

https://tools.hmcts.net/jira/browse/BPS-1219
add staging db infra
```
[ ] Yes
[x] No
```

add staging db infra

---

charts/reform-scan-notification-service/values.aat.template.yaml
src/main/resources/bootstrap.yaml

https://tools.hmcts.net/jira/browse/BPS-1219
bootstrap new staging values
```
[ ] Yes
[x] No
```

add staging secrets

---

src/main/resources/bootstrap.yaml

Fix staging db conf
```
[ ] Yes
[x] No
```

fix staging db conf

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/BPS-1221
search notification by date
controller will come in next PR.
```
[ ] Yes
[x] No
```

search notification by date

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java

https://tools.hmcts.net/jira/browse/BPS-1221
add notification end point
```
[ ] Yes
[x] No
```

add notification end point

---

infrastructure/main.tf

[AKS tests - notification service](https://tools.hmcts.net/jira/browse/BPS-1233)
for aks tests this has to be within same resource group
```
[ ] Yes
[x] No
```

Copy test s2s secret

---

infrastructure/main.tf

Apparently this wasn't as obvious as I anticipated in the first place. Fixing that
```
[ ] Yes
[x] No
```

Fix resource group for s2s vault

---

Jenkinsfile_CNP
src/functionalTest/resources/servicebus/message/valid-notification.json

Partially related to [AKS tests - notification service](https://tools.hmcts.net/jira/browse/BPS-1233)
Depends on #147 
```
[ ] Yes
[x] No
```

Use new secret in pipeline for functional tests

---

build.gradle
config/owasp/suppressions.xml

fix dependabot and suppression
```
[ ] Yes
[x] No
```

fix dependabot and suppression

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationStatus.java

https://tools.hmcts.net/jira/browse/BPS-1268
add new status manually handled
```
[ ] Yes
[x] No
```

add new status manually handled

---

src/main/resources/db/migration/V008__Add_message_id_column_notifications.sql

https://tools.hmcts.net/jira/browse/BPS-1291
```
[ ] Yes
[x] No
```

Add message id to notifications table

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/resources/db/migration/V009__populate-message-id-values-add-unique-constraint.sql

Re-opening PR #191
```
[ ] Yes
[x] No
```

Populate null message id values and add unique constraint 

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java
src/main/java/uk/gov/hmcts/reform/notificationservice/exception/DuplicateMessageIdException.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandler.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java

https://tools.hmcts.net/jira/browse/BPS-1291
Handle the duplicate notification message ids:
- Dead letter the message and log error if it is the first delivery of the message
- Complete the message and log warning if it is NOT the first delivery of the message
```
[ ] Yes
[x] No
```

Handle duplicate notification messages

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java

https://tools.hmcts.net/jira/browse/BPS-1310
This log entry is used for alert so comment added to prevent any change
```
[ ] Yes
[x] No
```

Added comment for log used for alert

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java

log prefetch count to share the count with MS
after getting the count from prod will be reverted.
```
[ ] Yes
[ ] No
```

log prefetch count

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java

Revert "log prefetch count (#203)"
```
[ ] Yes
[x] No
```

Revert "log prefetch count (#203)"

---

build.gradle

This reverts commit 56417f14
```
[ ] Yes
[x] No
```

Revert "Bump postgresql from 42.2.14 to 42.2.15 (#225)"

---

src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java

Disable notifications functional test

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/resources/application.yaml

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
```
[ ] Yes
[x] No
```

Use new config for ServiceBus connection

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/application.yaml

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
aat template must use different queue name
```
[ ] Yes
[x] No
```

Fix queue name config

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/application.yaml
src/main/resources/bootstrap.yaml

[Improve the way Service Bus clients are created](https://tools.hmcts.net/jira/browse/BPS-771)
```
[ ] Yes
[x] No
```

Remove ServiceBus connection string from chart

---

build.gradle

Fixes the testconainers issue related to 2.4.0 upgrade. 
```
[ ] Yes
[X] No
```

fix: bump testcontainers to latest RC

---

build.gradle
config/owasp/suppressions.xml

dependabot upgrades
```
[ ] Yes
[x] No
```

dependabot upgrades

---

Jenkinsfile_CNP
charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/requirements.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml

Upgrade chart
```
[ ] Yes
[ ] No
```

Upgrade chart

---

build.gradle

bump shedlocks and springdoc-openapi
```
[ ] Yes
[x] No
```

bump shedlocks and springdoc-openapi

---

config/owasp/suppressions.xml

suppress lang-tag vulnerability

---

build.gradle

bump org.assert
```
[ ] Yes
[x] No
```

bump org.assert

---

build.gradle

Bump postgresql from 42.2.14 to 42.2.19 #383

Bump postgresql from 42.2.14 to 42.2.19 #383

---

build.gradle

can not find the version 38 for com.github.ben-manes.versions
```
[ ] Yes
[x] No
```

downgrade  com.github.ben-manes.versions

---

build.gradle

dependabot bumps
```
[ ] Yes
[x] No
```

dependabot bumps

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java
src/main/java/uk/gov/hmcts/reform/notificationservice/model/out/NotificationsResponse.java

Total counts for notifications with sent and pending status are added.
Test cases updated too.
```
[ ] Yes
[ x] No
```

count for sent and pending notifications added

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-496
Add log for messagelost exception
```
[ ] Yes
[x] No
```

DTSBPS-496 Add log for message lost exception

---

build.gradle
src/main/java/uk/gov/hmcts/reform/notificationservice/Application.java

remove spring-cloud-starter-netflix-hystrix
```
[ ] Yes
[x] No
```

remove spring-cloud-starter-netflix-hystrix

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java
src/main/java/uk/gov/hmcts/reform/notificationservice/model/out/NotificationInfo.java

https://tools.hmcts.net/jira/browse/DTSBPS-530
```
[ ] Yes
[x] No
```

Added error description to report

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-532
refactor test
```
[ ] Yes
[x] No
```

DTSBPS-532 refactor test

---

build.gradle

dependabot bump flyway
```
[ ] Yes
[x] No
```

dependabot bump flyway

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java

https://tools.hmcts.net/jira/browse/DTSBPS-600
```
[ ] Yes
[x] No
```

Search by file name - repo

---

src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-600
```
[ ] Yes
[x] No
```

Find by zip file name - service layer

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationControllerTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java

https://tools.hmcts.net/jira/browse/DTSBPS-600
```
[ ] Yes
[x] No
```

Find by zip file name - controller layer

---

src/main/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepository.java

https://tools.hmcts.net/jira/browse/DTSBPS-600
```
[ ] Yes
[x] No
```

Defined constant to fix quality gateway failure

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/Configuration.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageDetails.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageHelper.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParser.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-616
Use new servicebus lib
```
[ ] Yes
[x] No
```

DTSBPS-616 Use new servicebus lib

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/Configuration.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageDetails.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageHelper.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParser.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

Revert #503  servicebus upgrade 
```
[ ] Yes
[ ] No
```

Revert servicebus upgrade

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/Configuration.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/ProcessNotificationTest.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageDetails.java
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/QueueMessageHelper.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/QueueClientConfig.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParser.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java
src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

DTSBPS-616 
DTSBPS-616 Use new servicebus lib #508
```
[ ] Yes
[x] No
```

 DTSBPS-616 Use new servicebus lib

---

build.gradle

remove unnecessary jars dependency management
```
[ ] Yes
[x] No
```

remove unnecessary jars dependency management

---

build.gradle

Bump org.springframework.boot from 2.5.0 to 2.5.1 #516
```
[ ] Yes
[x] No
```

Bump org.springframework.boot from 2.5.0 to 2.5.1

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

upgrade gradle version
```
[ ] Yes
[x] No
```

upgrade gradle version

---

build.gradle
src/integrationTest/resources/application.properties
src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
src/main/resources/application.yaml
src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-637
add check for queue listener.
we need to alert if the listener is not working
```
[ ] Yes
[x] No
```

DTSBPS-637 add check for queue listener

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-637
add new env. var for check job
```
[ ] Yes
[x] No
```

DTSBPS-637 - add new env. var for check job

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
charts/reform-scan-notification-service/values.yaml
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-637
use new var and remove old one.
```
[ ] Yes
[x] No
```

DTSBPS-637 use new env var

---

src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

fix assertion in tests
```
[ ] Yes
[x] No
```

fix assertion in tests

---

charts/reform-scan-notification-service/Chart.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-650
upgrade java chart
```
[ ] Yes
[x] No
```

DTSBPS-650 upgrade java chart

---

build.gradle

downgrade 'azure-messaging-servicebus'
seems it did not picked up 2 messages.
```
[ ] Yes
[x] No
```

downgrade 'azure-messaging-servicebus'

---

build.gradle

dependabot  postgresql and jupiter 
```
[ ] Yes
[x] No
```

dependabot  postgresql and jupiter

---

build.gradle

upgrade feign-jackson 11.5
```
[ ] Yes
[x] No
```

upgrade feign-jackson 11.5

---

charts/reform-scan-notification-service/Chart.yaml

DTSBPS-692 bump java chart
```
[ ] Yes
[x] No
```

DTSBPS-692 bump java chart

---

src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationServiceTest.java

DTSBPS-695 remove feign exception creation
```
[ ] Yes
[x] No
```

DTSBPS-695 remove feign exception creation

---

.dependabot/config.yml
.github/dependabot.yml

DTSBPS-706
use git native dependabot
```
[ ] Yes
[x] No
```

DTSBPS-706 use git native dependabot

---

src/test/java/uk/gov/hmcts/reform/notificationservice/service/AuthServiceTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageHandlerTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageMapperTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageParserTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessorTest.java
src/test/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTaskTest.java

https://tools.hmcts.net/jira/browse/DTSBPS-736
```
[ ] Yes
[x] No
```

Code smells

---

build.gradle

bump to azure-messaging-servicebus 7.4.1
```
[ ] Yes
[x] No
```

bump to azure-messaging-servicebus 7.4.1

---

build.gradle

bump versions-failed depabot PRs
```
[ ] Yes
[x] No
```

bump versions-failed depabot PRs

---

build.gradle

arrange bump hmcts jars
```
[ ] Yes
[x] No
```

arrange bump hmcts jars

---

build.gradle

DTSBPS-804 upgrade spring boot 2.6.1
```
[ ] Yes
[x] No
```

DTSBPS-804 upgrade spring boot 2.6.1

---

build.gradle

remove netty dependency management
```
[ ] Yes
[ ] No
```

remove netty dependency management

---

build.gradle

DTSBPS-841 remove jcenter
```
[ ] Yes
[x] No
```

DTSBPS-841 remove jcenter

---

build.gradle
config/owasp/suppressions.xml

https://github.com/hmcts/blob-router-service/pull/1328
```
[ ] Yes
[x] No
```

Suppress CVE-2022-23181

---

charts/reform-scan-notification-service/Chart.yaml

bump-java-chart
```
[ ] Yes
[x] No
```

bump-java-chart

---

charts/reform-scan-notification-service/Chart.yaml

bump java chart
```
[ ] Yes
[x] No
```

bump java chart

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.yaml

DTSBPS-891 use premium service bus
```
[ ] Yes
[x] No
```

DTSBPS-891 use premium service bus

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-916
- Upgrade spring-boot version to 2.6.6
- cleanup suppressions.xml
```
[ ] Yes
[x] No
```

Upgrade spring-boot version

---

build.gradle
config/owasp/suppressions.xml

DTSBPS-978: Fix CVE 2022 22978

---

config/owasp/suppressions.xml

Suppress CVE-2022-34305
```
[ ] Yes
[x] No
```

Suppress CVE-2022-34305

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/DTSBPS-1016
Bump java chart version
```
[ ] Yes
[x] No
```

Bump java chart version

---

Dockerfile
charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml
lib/AI-Agent.xml
lib/applicationinsights.json
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationService.java

Revert "DTSBPS-1070 upgrade app-insight (#999)"

Revert "DTSBPS-1070 upgrade app-insight (#999)"

---

Dockerfile
build.gradle
config/checkstyle/checkstyle.xml
src/main/java/uk/gov/hmcts/reform/notificationservice/controller/NotificationController.java
src/main/java/uk/gov/hmcts/reform/notificationservice/service/NotificationMessageProcessor.java

Revert "DTSBPS-1070 upgrade to java 17 (#998)"

Revert "DTSBPS-1070 upgrade to java 17 (#998)"

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml

DTSBPS-1070 add app-insight-connection

DTSBPS-1070 add app-insight-connection

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml
infrastructure/app-insights.tf
lib/applicationinsights.json

DTSBPS-1070 upgrade app-insight

DTSBPS-1070 upgrade app-insight

---

Jenkinsfile_CNP

use java-17 for Jenkinsfile_CNP

use java-17 for Jenkinsfile_CNP

---

Jenkinsfile_CNP

Revert "use jdk17 Jenkinsfile_CNP (#1009)"

Revert "use jdk17 Jenkinsfile_CNP (#1009)"

---

config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1097
Add suppressions for tomcat-embed libraries
```
[ ] Yes
[x] No
```

Add suppression for tomcat libraries

---

build.gradle

Upgraded junit-jupiter

---

Dockerfile

https://tools.hmcts.net/jira/browse/DTSBPS-1258
```
[ ] Yes
[x] No
```

DTSBPS-1258: Upgraded AppInsights to the latest version

---

infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/DTSBPS-1294
```
[ ] Yes
[x] No
```

DTSBPS-1294: Removed unused variable ilbIp

---

build.gradle
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/DTSBPS-1325
```
[ ] Yes
[x] No
```

DTSBPS-1325: Fix CVE 2023 24998

---

build.gradle
charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml
config/owasp/suppressions.xml
infrastructure/main.tf
infrastructure/provider.tf
infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf
infrastructure/variables.tf

https://tools.hmcts.net/jira/browse/FACT-1514
- Created new flexible databases
- Infra code setup for storing secrets in key vault
- General format of terraform files
```
[ ] Yes
[x] No
```

FACT-1514 Postgres flexible servers

---

charts/reform-scan-notification-service/values.aat.template.yaml
config/owasp/suppressions.xml

https://tools.hmcts.net/jira/browse/FACT-1530
Change AAT to use correct service bus as current one is getting removed because no longer need and to save cost.
```
[ ] Yes
[x] No
```

FACT-1530 change aat to use correct servicebus

---

Jenkinsfile_CNP

Using notification queue for now until staging is back in

fixing aat

---

charts/reform-scan-notification-service/values.aat.template.yaml
config/owasp/suppressions.xml

Changed back sb var for notification queue to stg.
```
[ ] Yes
[x] No
```

changed back var for notif queue

---

Jenkinsfile_CNP
charts/reform-scan-notification-service/values.aat.template.yaml

Updated SB to be used for aat/stg tests

Updated SB to be used in tests

---

config/owasp/suppressions.xml

Removed suppression date, still unable to fix atm. Fix nightly builds
```
[ ] Yes
[x] No
```

Suppression date change

---

build.gradle
config/owasp/suppressions.xml
src/smokeTest/java/uk/gov/hmcts/reform/notificationservice/LaunchDarklySmokeTest.java

cve updates

---

infrastructure/tf-db-flexible.tf

Made db host name shorter due to max length error in perf test.
```
[ ] Yes
[x] No
```

Updated host name as its too long

---

charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml

https://tools.hmcts.net/jira/browse/FACT-1632
Switch to use flex creds by default for DB.
```
[ ] Yes
[x] No
```

FACT-1632 switch to use flex creds

---

build.gradle
src/functionalTest/java/uk/gov/hmcts/reform/notificationservice/JmsNotificationsMessageSender.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/config/SwaggerPublisher.java
src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/health/ReadinessTest.java
src/main/java/uk/gov/hmcts/reform/notificationservice/Application.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/HttpConfiguration.java
src/main/java/uk/gov/hmcts/reform/notificationservice/config/jms/JmsConfiguration.java
src/main/java/uk/gov/hmcts/reform/notificationservice/task/NotificationMessageProcessTask.java
src/main/resources/application-dev.yaml

spingboot 3 initial changes

---

infrastructure/tf-db-flexible.tf

recreate roles/access [DO NOT MERGE TILL RELEASE]
```
[ ] Yes
[x] No
```

recreate roles/access

---

infrastructure/tf-db-flexible.tf

- schema ownership fix [DO NOT MERGE TILL RELEASE] #2189
```
[ ] Yes
[x] No
```

schema ownership fix [DO NOT MERGE TILL RELEASE] #2189

---

README.md
charts/reform-scan-notification-service/Chart.yaml
charts/reform-scan-notification-service/values.yaml

https://tools.hmcts.net/jira/browse/FACT-1662
Switch chart to use correct values.
```
[ ] Yes
[x] No
```

Switch chart to use correct values

---

infrastructure/state.tf

Update azurerm
```
[ ] Yes
[x] No
```

Updated azurerm

---

src/main/resources/db/migration/V010__add_calling_client.sql

Adding migration only for FACT-1819

adding migration only for demo

---

src/main/resources/db/migration/V011__set_client_not_null.sql

https://tools.hmcts.net/jira/browse/FACT-1828
DB script to fix null issue.
```
[ ] Yes
[x] No
```

FACT-1828 DB script

---

Dockerfile
build.gradle
config/owasp/suppressions.xml
gradle/wrapper/gradle-wrapper.properties

J21 and build gradle updates for CVE

updates j21 build gradle

---

charts/reform-scan-notification-service/values.aat.template.yaml
charts/reform-scan-notification-service/values.preview.template.yaml

https://tools.hmcts.net/jira/browse/FACT-1839
Switch to temp db over dedicated db for aat master builds.
```
[ ] Yes
[x] No
```

FACT-1839 switch to temp db

---

Jenkinsfile_CNP
Jenkinsfile_nightly
charts/reform-scan-notification-service/Chart.yaml
docker/database/Dockerfile

https://tools.hmcts.net/jira/browse/FACT-1881
trying to change to imported image and bumps
```
[ ] Yes
[x] No
```

FACT-1881 changes to servicebus and docker image

---

infrastructure/tf-db-flexible-secrets.tf
infrastructure/tf-db-flexible.tf

https://tools.hmcts.net/jira/browse/FACT-1839
Remove unused db
```
[ ] Yes
[x] No
```

FACT-1839 remove unused db

---

.github/workflows/ci.yml
.github/workflows/publish-openapi.yaml
Dockerfile
README.md
build.gradle
gradle/wrapper/gradle-wrapper.properties
src/main/resources/application.yaml

https://tools.hmcts.net/jira/browse/FACT-1802
java 17 to 21
```
[ ] Yes
[x] No
```

FACT-1802 17 to 21 changes

---

.gitignore
build.gradle

https://tools.hmcts.net/jira/browse/FACT-1802
missing flyway variable
```
[ ] Yes
[x] No
```

FACT-1802 added missing flyway version variable

---

src/integrationTest/java/uk/gov/hmcts/reform/notificationservice/data/NotificationRepositoryTest.java
src/main/resources/db/migration/V012__remove_message_id_constraint.sql

This reverts commit 3e2a1b7f6a410b850e59d21752d3c08233cb6d9f.
https://tools.hmcts.net/jira/browse/FACT-1963
This reverts the commit added for testing FACT-1963
```
[ ] Yes
[x] No
```

Revert "FACT-1963 Adds db migration script for testing (#1620)"

---

build.gradle
charts/reform-scan-notification-service/Chart.yaml
gradle/wrapper/gradle-wrapper.properties

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

FACT-2294 updates

---

.github/renovate.json
renovate.json

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

FACT-2429 removed old and added new renovate

---

build.gradle

**Before creating a pull request make sure that:**
Please remove this line and everything above and fill the following sections:
```
[ ] Yes
[ ] No
```

FACT-2449 added fortify client
